# Other Industrial and Commercial Processes

```{r indcom-bakeries, child="04-indcom/indcom-bakeries.Rmd"}
```

***

```{r indcom-cooking, child="04-indcom/indcom-cooking.Rmd"}
```

***

```{r indcom-wineries-fermentation, child="04-indcom/indcom-wineries-fermentation.Rmd"}
```

***

```{r indcom-wineries-aging, child="04-indcom/indcom-wineries-aging.Rmd"}
```

***

```{r indcom-food_ag-other, child="04-indcom/indcom-food_ag-other.Rmd"}
```

***

```{r indcom-metal, child="04-indcom/indcom-metal.Rmd"}
```

***

```{r indcom-wood, child="04-indcom/indcom-wood.Rmd"}
```

***

```{r indcom-cement, child="04-indcom/indcom-cement.Rmd"}
```

***

```{r indcom-soil-aeration, child="04-indcom/indcom-soil-aeration.Rmd"}
```

***

```{r indcom-soil-vapor_ext, child="04-indcom/indcom-soil-vapor_ext.Rmd"}
```

***

```{r indcom-concrete-asphaltic, child="04-indcom/indcom-concrete-asphaltic.Rmd"}
```

***

```{r indcom-concrete-batching, child="04-indcom/indcom-concrete-batching.Rmd"}
```

***

```{r indcom-glass, child="04-indcom/indcom-glass.Rmd"}
```

***

```{r indcom-stone_sand_gravel, child="04-indcom/indcom-stone_sand_gravel.Rmd"}
```

***

```{r indcom-sandblast, child="04-indcom/indcom-sandblast.Rmd"}
```

***

```{r indcom-mfg-semicond, child="04-indcom/indcom-mfg-semicond.Rmd"}
```

***

```{r indcom-mfg-discs, child="04-indcom/indcom-mfg-discs.Rmd"}
```

***

```{r indcom-mfg-fiberglass, child="04-indcom/indcom-mfg-fiberglass.Rmd"}
```

***

```{r indcom-mfg-rubber, child="04-indcom/indcom-mfg-rubber.Rmd"}
```

***

```{r indcom-mfg-plastic, child="04-indcom/indcom-mfg-plastic.Rmd"}
```

***

```{r indcom-oil_fields, child="04-indcom/indcom-oil_fields.Rmd"}
```

***

```{r indcom-gas_fields, child="04-indcom/indcom-gas_fields.Rmd"}
```

***

```{r indcom-other_misc, child="04-indcom/indcom-other_misc.Rmd"}
```
