## Resource Recovery

### Emissions

#### Introduction {-}

There were no sources operating within this category. Years ago, some permit applications for proposed resource recovery facilities had been submitted to the District for evaluation. None apparently completed the permit evaluation process (i.e., received a Permit to Operate) and none were operating. Consequently, there were no emissions for Category 313.

#### Methodology {-}

There were no sources operating within this category, therefore no reported emissions.

In general, the District collects fuel usage data each year on a source-by-source basis from point source facilities operating in the Bay Area. Emissions are calculated using fuel usage data and emission factors in the database. Emission and control factors used are either source specific as reported by the plants or general factors, i.e., from the Environmental Protection Agency (EPA); the U.S. Department of Energy’s (DOE’s) Energy Information Administration (EIA); California Energy Commission (CEC) etc.

### Trends

#### History {-}

There is no historical data for this category.

#### Growth {-}

No sources are projected to operate in this category.

#### Control {-}

No sources are subject to any combustion rules.

By: Sukarn Claire 
Date: January 2014 
Base Year: 2011
