#### Motor Vehicles Assembly Plants {#petprod-coat-indcom-auto-assembly}

```{r petprod-coat-indcom-auto-assembly-setup}
AUTO_ASSEMBLY_CATEGORIES <- c(
  "#272 Auto Assembly Ctg." = 272,
  "#273 Auto Assembly C/U" = 273) # "C/U" means "cleanup solvent"
```

##### County Fractions {-}

```{r petprod-coat-indcom-auto-assembly-county-fraction-table}
BY2011_county_fraction_data %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  kable_BY2011_county_fractions()
```

##### History {-}

```{r petprod-coat-indcom-auto-assembly-emission-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  chart_BY2011_annual_emissions_by(
    fill = category) 
```

##### Emission Factors (Area) {-}

**N/A**

##### Growth {-}

```{r petprod-coat-indcom-auto-assembly-growth-crosswalk}
BY2011_growth_profile_crosswalk %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  kable_BY2011_growth_crosswalk()
```

```{r petprod-coat-indcom-auto-assembly-growth-chart}
BY2011_annual_growth_factor_data %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  chart_BY2011_annual_growth_factors_by(
    color = cnty_abbr) 
```

##### Control {-}

```{r petprod-coat-indcom-auto-assembly-control-chart, fig.height=2, out.height=200}
BY2011_annual_control_factor_data %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  chart_BY2011_annual_control_factors_by(
    color = pollutant) 
```

##### BY2011 vs DataBank (Point) {-}

```{r petprod-coat-indcom-auto-assembly-BY-vs-DB-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    AUTO_ASSEMBLY_CATEGORIES) %>%
  chart_BY_vs_DB_point_source_annual_emissions()
```
