#### Auto Refinishing {#petprod-coat-indcom-auto-refinish}

```{r petprod-coat-indcom-auto-refinish-setup}
AUTO_REFINISH_CATEGORIES <- c(
  "#274 Auto Refinishing Ctg." = 274,
  "#275 Auto Refinishing C/U" = 275, # "C/U" means "cleanup solvent"
  "#1928 Auto Refinishing Ctg. (Area)" = 1928,
  "#1929 Auto Refinishing C/U (Area)" = 1929)
```

##### County Fractions {-}

```{r petprod-coat-indcom-auto-refinish-county-fraction-table}
BY2011_county_fraction_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  kable_BY2011_county_fractions()
```

##### History {-}

```{r petprod-coat-indcom-auto-refinish-emission-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  chart_BY2011_annual_emissions_by(
    fill = category) 
```

##### Emission Factors (Area) {-}

```{r petprod-coat-indcom-auto-refinish-emfac-chart, fig.height=3, out.height=300}
BY2011_annual_area_source_emission_factor_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  chart_BY2011_annual_emission_factors_by(
    color = category)
```

##### Growth {-}

```{r petprod-coat-indcom-auto-refinish-growth-crosswalk}
BY2011_growth_profile_crosswalk %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  kable_BY2011_growth_crosswalk()
```

```{r petprod-coat-indcom-auto-refinish-growth-chart, fig.height=6, out.height=600}
BY2011_annual_growth_factor_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  chart_BY2011_annual_growth_factors_by(
    color = cnty_abbr) 
```

##### Control {-}

```{r petprod-coat-indcom-auto-refinish-control-chart, fig.height=6, out.height=600}
BY2011_annual_control_factor_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  chart_BY2011_annual_control_factors_by(
    color = pollutant) 
```

##### BY2011 vs DataBank (Point) {-}

```{r petprod-coat-indcom-auto-refinish-BY-vs-DB-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    AUTO_REFINISH_CATEGORIES) %>%
  chart_BY_vs_DB_point_source_annual_emissions()
```
