#### Can & Coil Coating {#coat-indcom-can_coil}

```{r petprod-coat-indcom-can_coil-setup}
CAN_COIL_CATEGORIES <- c(
  "#252 Can & Coil Ctg." = 262,
  "#253 Can & Coil C/U" = 253)
```

##### History {-}

```{r petprod-coat-indcom-can_coil-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    CAN_COIL_CATEGORIES) %>%
  chart_BY2011_annual_emissions_by(
    fill = category) 
```

##### Emission Factors (Area) {-}

**N/A**

##### Growth {-}

```{r petprod-coat-indcom-can_coil-growth-chart}
BY2011_annual_growth_factor_data %>%
  filter_categories(
    CAN_COIL_CATEGORIES) %>%
  chart_BY2011_annual_growth_factors_by(
    color = cnty_abbr) 
```

##### Control {-}

```{r petprod-coat-indcom-can_coil-control-chart}
BY2011_annual_control_factor_data %>%
  filter_categories(
    CAN_COIL_CATEGORIES) %>%
  chart_BY2011_annual_control_factors_by(
    color = pollutant) 
```

##### BY2011 vs DataBank (Point) {-}

```{r petprod-coat-indcom-can_coil-BY-vs-DB-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    CAN_COIL_CATEGORIES) %>%
  chart_BY_vs_DB_point_source_annual_emissions()
```
