#### Fabric & Film Coating {#coat-indcom-fabric_film}

```{r petprod-coat-indcom-fabric_film-setup}
FABRIC_FILM_CATEGORIES <- c(
  "#260 Fabric & Film Ctg." = 260,
  "#261 Fabric & Film C/U" = 261,
  "#1918 Fabric & Film Ctg. (Area)" = 1918,
  "#1919 Fabric & Film C/U (Area)" = 1919)
```

##### History {-}

```{r petprod-coat-indcom-fabric_film-annual_emissions-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    FABRIC_FILM_CATEGORIES) %>%
  chart_BY2011_annual_emissions_by(
    fill = category) 
```

##### Emission Factors (Area) {-}

```{r petprod-coat-indcom-fabric_film-annual_emission_factor-chart}
BY2011_annual_area_source_emission_factor_data %>%
  filter_categories(
    FABRIC_FILM_CATEGORIES) %>%
  chart_BY2011_annual_emission_factors_by(
    color = category)
```

##### Growth {-}

```{r petprod-coat-indcom-fabric_film-annual_growth-chart, fig.height=6, out.height=600}
BY2011_annual_growth_factor_data %>%
  filter_categories(
    FABRIC_FILM_CATEGORIES) %>%
  chart_BY2011_annual_growth_factors_by(
    color = cnty_abbr) 
```

##### Control {-}

```{r petprod-coat-indcom-fabric_film-annual_control-chart}
BY2011_annual_control_factor_data %>%
  filter_categories(
    FABRIC_FILM_CATEGORIES) %>%
  chart_BY2011_annual_control_factors_by(
    color = pollutant) 
```

##### BY2011 vs DataBank (Point) {-}

```{r petprod-coat-indcom-fabric_film-BY_vs_DB-emissions_chart}
BY2011_annual_emission_data %>%
  filter_categories(
    FABRIC_FILM_CATEGORIES) %>%
  chart_BY_vs_DB_point_source_annual_emissions()
```
