#### Large Appliances & Metal Furniture {#petprod-coat-indcom-large-appliance}

```{r petprod-coat-indcom-large-appliance-setup}
LARGE_APPLIANCE_CATEGORIES <- c(
  "#266 Large Appliances & Metal Furniture Ctg." = 266,
  "#267 Large Appliances & Metal Furniture C/U" = 267, # "C/U" means "cleanup solvent"
  "#1924 Large Appliances & Metal Furniture Ctg. (Area)" = 1924,
  "#1925 Large Appliances & Metal Furniture C/U (Area)" = 1925)
```

##### County Fractions {-}

```{r petprod-coat-indcom-large-appliance-county-fraction-table}
BY2011_county_fraction_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  kable_BY2011_county_fractions()
```

##### History {-}

```{r petprod-coat-indcom-large-appliance-emission-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  chart_BY2011_annual_emissions_by(
    fill = category) 
```

##### Emission Factors (Area) {-}

```{r petprod-coat-indcom-large-appliance-emfac-chart}
BY2011_annual_area_source_emission_factor_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  chart_BY2011_annual_emission_factors_by(
    color = category)
```

##### Growth {-}

```{r petprod-coat-indcom-large-appliance-growth-crosswalk}
BY2011_growth_profile_crosswalk %>%
  filter_categories(
    THESE_CATEGORIES) %>%
  kable_BY2011_growth_crosswalk()
```

```{r petprod-coat-indcom-large-appliance-growth-chart, fig.height=6, out.height=600}
BY2011_annual_growth_factor_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  chart_BY2011_annual_growth_factors_by(
    color = cnty_abbr) 
```

##### Control {-}

```{r petprod-coat-indcom-large-appliance-control-chart}
BY2011_annual_control_factor_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  chart_BY2011_annual_control_factors_by(
    color = pollutant) 
```

##### BY2011 vs DataBank (Point) {-}

```{r petprod-coat-indcom-large-appliance-BY-vs-DB-chart}
BY2011_annual_emission_data %>%
  filter_categories(
    LARGE_APPLIANCE_CATEGORIES) %>%
  chart_BY_vs_DB_point_source_annual_emissions()
```
