```{r appendix-rules_and_regs}
#
# Full listing: https://www.baaqmd.gov/rules-and-compliance/current-rules
#
```

[Regulation 2]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-permits "Regulation 2: Permits"

[Rule 2-1]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-1-general-requirements "Regulation 2, Rule 1: General Requirements"

[Rule 2-2]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-2-new-source-review "Regulation 2, Rule 2: New Source Review"

[Rule 2-3]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-3-power-plants "Regulation 2, Rule 3: Power Plants"

[Rule 2-4]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-4-emissions-banking "Regulation 2, Rule 4: Emissions Banking"

[Rule 2-5]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-5-new-source-review-of-toxic-air-contaminants "Regulation 2, Rule 5: New Source Review of Toxic Air Contaminants"

[Rule 2-6]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-6-major-facility-review "Regulation 2, Rule 6: Major Facility Review"

[Rule 2-7]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-7-acid-rain "Regulation 2, Rule 7: Acid Rain"

[Rule 2-9]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-9-interchangeable-emission-reduction-credits "Regulation 2, Rule 9: Interchangeable Emission Reduction Credits"

[Rule 2-10]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-2-rule-10-large-confined-animal-facilities "Regulation 2, Rule 10: Large Confined Animal Facilities"

[Regulation 3]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-3-fees?rule_version=2019%20Amendment "Regulation 3: Fees"

[Regulation 4]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-4-air-pollution-episode-plan "Regulation 4: Air Pollution Episode Plan"

[Regulation 5]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-5-open-burning?rule_version=2019%20Amendment "Regulation 5: Open Burning"

[Regulation 6]: https://www.baaqmd.gov/rules-and-compliance/rules/regulation-6-particulate-matter---common-definitions-and-test-methods "Regulation 6: Particulate Matter - Common Definitions and Test Methods"

[Rule 6-1]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-6-rule-1-general-requirements?rule_version=2018%20Amendment "Regulation 6, Rule 1: General Requirements 2018 Amendment"

[Rule 6-2]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-6-rule-2-commercial-cooking-equipment "Regulation 6, Rule 2: Commercial Cooking Equipment"

[Rule 6-3]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-6-rule-3-woodburning-devices?rule_version=Under%20Development "Regulation 6, Rule 3: Wood-burning Devices 2019 Amendment"

[Rule 6-4]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-6-rule-4--metal-recycling-and-shredding-operations "Metal Recycling and Shredding Operations"

[Rule 6-5]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-6-rule-5-particulate-emissions-from-refinery-fluidized-catalytic-cracking-units?rule_version=2018%20Amendment "Regulation 6, Rule 5: Particulate Emissions from Refinery Fluidized Catalytic Cracking Units 2018 Amendment"

[Rule 6-6]: https://www.baaqmd.gov/rules-and-compliance/rules/regulation-6-rule-6-prohibition-of-trackout "Regulation 6, Rule 6: Prohibition of Trackout"

[Regulation 7]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-7-odorous-substances "Regulation 7: Odorous Substances"

[Regulation 8]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-organic-compounds "Regulation 8: Organic Compounds"

[Rule 8-1]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-1-general-provisions "Regulation 8, Rule 1: General Provisions"

[Rule 8-2]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-2-miscellaneous-operations "Regulation 8, Rule 2: Miscellaneous Operations"

[Rule 8-3]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-3-architectural-coatings "Regulation 8, Rule 3: Architectural Coatings"

[Rule 8-4]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-4-general-solvent-and-surface-coating-operations "Regulation 8, Rule 4: General Solvent and Surface Coating Operations"

[Rule 8-5]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-5-storage-of-organic-liquids "Regulation 8, Rule 5: Storage of Organic Liquids"

[Rule 8-6]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-6-terminals-and-bulk-plants "Regulation 8, Rule 6: Terminals and Bulk Plants"

[Rule 8-7]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-7-gasoline-dispensing-facilities "Regulation 8, Rule 7: Gasoline Dispensing Facilities"

[Rule 8-8]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-8-wastewater-oilwater-separators "Regulation 8, Rule 8: Wastewater (Oil-Water) Separators"

[Rule 8-9]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-9-vacuum-producing-systems "Regulation 8, Rule 9: Vacuum Producing Systems"

[Rule 8-10]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-10-process-vessel-depressurization "Regulation 8, Rule 10: Process Vessel Depressurization"

[Rule 8-11]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-11-metal-container-closure-and-coil-coating "Regulation 8-11: Metal Container, Closure and Coil Coating"

[Rule 8-12]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-12-paper-fabric-and-film-coating "Regulation 8, Rule 12: Paper, Fabric, and Film Coating"

[Rule 8-13]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-13-light-and-medium-duty-motor-vehicle-assembly-plants "Regulation 8, Rule 13: Light and Medium Duty Motor Vehicle Assembly Plants"

[Rule 8-14]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-14-surface-coating-of-large-appliances-and-metal-furniture "Regulation 8, Rule 14: Surface Coating of Large Appliances and Metal Furniture"

[Rule 8-15]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-15-emulsified-and-liquid-asphalts "Regulation 8, Rule 15: Emulsified and Liquid Asphalts"

[Rule 8-16]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-16-solvent-cleaning-operations "Regulation 8, Rule 16: Solvent Cleaning Operations"

[Rule 8-17]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-17-petroleum-dry-cleaning-operations "Regulation 8, Rule 17: Petroleum Dry Cleaning Operations"

[Rule 8-18]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-18-equipment-leaks "Regulation 8, Rule 18: Equipment Leaks"

[Rule 8-19]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-19-surface-coating-of-miscellaneous-metal-parts-and-products "Regulation 8, Rule 19: Surface Coating of Miscellaneous Metal Parts and Products"

[Rule 8-20]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-20-graphic-arts-printing-and-coating-operations "Regulation 8, Rule 20: Graphic Arts Printing and Coating Operations"

[Rule 8-21]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-21-rubber-tire-manufacturing-operations "Regulation 8, Rule 21: Rubber Tire Manufacturing Operations"

[Rule 8-22]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-22-valves-and-flanges-at-chemical-plants "Regulation 8, Rule 22: Valves and Flanges at Chemical Plants"

[Rule 8-23]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-23-coating-of-flat-wood-paneling-and-wood-flat-stock "Regulation 8, Rule 23: Coating of Flat Wood Paneling and Wood Flat Stock"

[Rule 8-24]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-24-pharmaceutical-and-cosmetic-manufacturing-operations "Regulation 8, Rule 24: Pharmaceutical and Cosmetic Manufacturing Operations"

[Rule 8-25]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-25-deleted-january-7-1998 "Regulation 8, Rule 25: Deleted January 7, 1998"

[Rule 8-26]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-26-magnet-wire-coating-operations "Regulation 8, Rule 26: Magnet Wire Coating Operations"

[Rule 8-27]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-27-deleted-march-4-2009 "Regulation 8, Rule 27: Deleted: March 4, 2009"

[Rule 8-28]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-28-episodic-releases-from-pressure-relief-devices-at-petroleum-refineries-and-chemical-pl "Regulation 8, Rule 28: Episodic Releases From Pressure Relief Devices at Petroleum Refineries and Chemical Plants"

[Rule 8-29]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-29-aerospace-assembly-and-component-coating-operations "Regulation 8, Rule 29: Aerospace Assembly and Component Coating Operations"

[Rule 8-30]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-30-semiconductor-wafer-fabrication-operations "Regulation 8, Rule 30: Semiconductor Wafer Fabrication Operations"

[Rule 8-31]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-31-surface-coating-of-plastic-parts-and-products "Regulation 8, Rule 31: Surface Coating of Plastic Parts and Products"

[Rule 8-32]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-32-wood-products-coatings "Regulation 8, Rule 32: Wood Products Coatings"

[Rule 8-33]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-33-gasoline-bulk-terminals-and-gasoline-delivery-vehicles "Regulation 8, Rule 33: Gasoline Bulk Terminals and Gasoline Delivery Vehicles"

[Rule 8-34]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-34-solid-waste-disposal-sites?rule_version=Adopted "Regulation 8, Rule 34: Solid Waste Disposal Sites"

[Rule 8-35]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-35-coating-ink-and-adhesive-manufacturing "Regulation 8, Rule 35: Coating, Ink and Adhesive Manufacturing"

[Rule 8-36]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-36-resin-manufacturing "Regulation 8, Rule 36: Resin Manufacturing"

[Rule 8-37]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-37-natural-gas-and-crude-oil-production-facilities "Regulation 8, Rule 37: Natural Gas and Crude Oil Production Facilities"

[Rule 8-38]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-38-flexible-and-rigid-disc-manufacturing "Regulation 8, Rule 38: Flexible and Rigid Disc Manufacturing"

[Rule 8-39]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-39-gasoline-bulk-plants-and-gasoline-delivery-vehicles "Regulation 8, Rule 39: Gasoline Bulk Plants and Gasoline Delivery Vehicles"

[Rule 8-40]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-40-aeration-of-contaminated-soil-and-removal-of-underground-storage-tanks "Regulation 8, Rule 40: Aeration of Contaminated Soil and Removal of Underground Storage Tanks"

[Rule 8-41]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-41-vegetable-oil-manufacturing-operations "Regulation 8, Rule 41: Vegetable Oil Manufacturing Operations"

[Rule 8-42]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-42-large-commercial-bread-bakeries "Regulation 8, Rule 42: Large Commercial Bread Bakeries"

[Rule 8-43]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-43-surface-coating-of-marine-vessels "Regulation 8, Rule 43: Surface Coating of Marine Vessels"

[Rule 8-44]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-44-marine-vessel-loading-terminals "Regulation 8, Rule 43: Marine Vessel Loading Terminals"

[Rule 8-45]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-45-motor-vehicle-and-mobile-equipment-coating-operations "Regulation 8, Rule 45: Motor Vehicle and Mobile Equipment Coating Operations"

[Rule 8-46]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-46-deleted-december-7-2005 "Regulation 8, Rule 46: Deleted: December 7, 2005"

[Rule 8-47]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-47-air-stripping-and-soil-vapor-extraction-operations "Regulation 8, Rule 47: Air Stripping and Soil Vapor Extraction Operations"

[Rule 8-48]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-48-deleted "Regulation 8, Rule 48: Deleted"

[Rule 8-49]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-49-aerosol-paint-products "Regulation 8, Rule 49: Aerosol Paint Products"

[Rule 8-50]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-50-polyester-resin-operations "Regulation 8, Rule 50: Polyester Resin Operations"

[Rule 8-51]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-51-adhesive-and-sealant-products "Regulation 8, Rule 51: Adhesive and Sealant Products"

[Rule 8-52]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-52-polystyrene-polypropylene-and-polyethylene-foam-product-manufacturing-operations-adopt "Regulation 8, Rule 52: Polystyrene, Polypropylene and Polyethylene Foam Product Manufacturing Operations"

[Rule 8-53]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-8-rule-53--vacuum-truck-operations "Regulation 8, Rule 53: Vacuum Truck Operations"

[Regulation 9]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-inorganic-gaseous-pollutants "Regulation 9: Inorganic Gaseous Pollutants"

[Rule 9-1]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-1-sulfur-dioxide "Regulation 9, Rule 1: Sulfur Dioxide"

[Rule 9-2]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-2-hydrogen-sulfide "Regulation 9, Rule 2: Hydrogen Sulfide"

[Rule 9-3]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-3-nitrogen-oxides-from-heat-transfer-operations "Nitrogen Oxides from Heat Transfer Operations"

[Rule 9-4]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-4-nitrogen-oxides-from-fan-type-residential-central-furnaces "Regulation 9, Rule 4: Nitrogen Oxides from Fan Type Residential Central Furnaces"

[Rule 9-5]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-5-hydrogen-sulfide-from-geothermal-power-plants "Regulation 9, Rule 5: Hydrogen Sulfide from Geothermal Power Plants"

[Rule 9-6]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-6-nitrogen-oxides-emissions-from-natural-gasfired-water-heaters "Regulation 9, Rule 6: Nitrogen Oxides Emissions from Natural Gas-Fired Water Heaters"

[Rule 9-7]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-7-nitrogen-oxides-and-carbon-monoxide-from-industrial-institutional-and-commercial-boiler "Regulation 9, Rule 7: Nitrogen Oxides And Carbon Monoxide from Industrial, Institutional, and Commercial Boilers, Steam Generators, And Process Heaters"

[Rule 9-8]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-8-nitrogen-oxides-and-carbon-monoxide-from-stationary-internal-combustion-engine "Regulation 9, Rule 8: Nitrogen Oxides And Carbon Monoxide from Stationary Internal Combustion Engines"

[Rule 9-9]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-9-nitrogen-oxides-and-carbon-monoxide-from-stationary-gas-turbine "Regulation 9, Rule 9: Nitrogen Oxides And Carbon Monoxide from Stationary Gas Turbines"

[Rule 9-10]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-10-nitrogen-oxides-and-carbon-monoxide-from-boiler-steam-generators-and-process-heaters "Regulation 9, Rule 10: Nitrogen oxides And Carbon Monoxide From Boilers, Steam Generators And Process Heaters in Petroleum Refineries"

[Rule 9-11]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-11-nitrogen-oxides-and-carbon-monoxide-from-utility-electric-power-generating-boiler "Regulation 9, Rule 11: Nitrogen Oxides And Carbon Monoxide from Utility Electric Power Generating Boilers"

[Rule 9-12]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-12-nitrogen-oxides-from-glass-melting-furnaces "Regulation 9, Rule 12: Nitrogen Oxides From Glass Melting Furnaces"

[Rule 9-13]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-9-rule-13--nitrogen-oxides-particulate-matter-and-toxic-air-contaminants-from-portland-cement-ma "Regulation 9, Rule 13: Nitrogen Oxides, Particulate Matter, and Toxic Air Contaminants from Portland Cement Manufacturing"

[Rule 9-14]: https://www.baaqmd.gov/rules-and-compliance/rules/regulation-9-rule-14--petroleum-coke-calcining-operations "Regulation 9, Rule 14: Petroleum Coke Calcining Operations"

[Regulation 10]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-10-standards-of-performance-for-new-stationary-sources "Regulation 10: Standards of Performance for New Stationary Sources"

[Regulation 11]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-11-hazardous-pollutants "Regulation 11: Hazardous Pollutants"

[Rule 11-16]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-11-rule-16-perchloroethylene-and-synthetic-solvent-dry-cleaning-operations "Regulation 11, Rule 16: Perchloroethylene and Synthetic Solvent Dry Cleaning Operations" 

[Regulation 12]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-12-miscellaneous-standards-of-performance "Regulation 12: Miscellaneous Standards of Performance"

[Rule 12-11]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-12-rule-11-flare-monitoring-at-petroleum-refineries "Regulation 12, Rule 11: Flare Monitoring at Petroleum Refineries"

[Rule 12-12]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-12-rule-12-flares-at-petroleum-refineries "Regulation 12, Rule 12: Flares at Petroleum Refineries"

[Rule 12-13]: https://www.baaqmd.gov/rules-and-compliance/rules/reg-12-rule-13--foundry-and-forging-operations "Regulation 12, Rule 13: Foundry and Forging Operations"

[Rule 12-15]: https://www.baaqmd.gov/rules-and-compliance/rules/regulation-12-rule-15--petroleum-refining-emissions-tracking?rule_version=Under%20Development "Regulation 12, Rule 15: Petroleum Refining Emissions Tracking 2019 Amendment"
